version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile 
    container_name: backend
    volumes:
      - ./:/home/app
    ports:
      - "4000:4000"
  
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls