version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile 
    container_name: backend
    volumes:
      - ./:/home/app
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db    

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8083:8081"